---
title: Błędy i wyjątki
subtitle: Podstawy programowania (AD) 2
author: Tomasz Rodak
---

# Błędy i wyjątki

## Czym są wyjątki ([Exceptions](https://docs.python.org/3/library/exceptions.html))?

- Wyjątki to błędy, które powstają podczas działania programu.
- W Pythona wbudowane jest wiele różnych wyjątków. Wyjątki te tworzą **hierarchię** opartą o dziedziczenie.
- Rodzaj powstałego wyjątku sugeruje rodzaj błędu.
- Po zgłoszeniu wyjątku mogą zdarzyć się różne rzeczy, w zależności od miejsca, w którym wyjątek został zgłoszony, zasadniczo jednak scenariusze są dwa:
  - wyjątek zostaje obsłużony w bloku `try` (o tym powiemy za chwilę);
  - wyjątek jest przekazywany na coraz wyższe poziomy programu, aż do momentu, w którym zostanie obsłużony albo program zostanie całkowicie przerwany.

## Przykłady wyjątków

- `ValueError` -- prawidłowy typ argumentu ale nieprawidłowa wartość.
- `IndexError` -- liczba całkowita nie jest indeksem sekwencji.
- `KeyError` -- obiekt nie jest kluczem słownika.
- `NameError` -- niezdefiniowana nazwa.
- `ZeroDivisionError` -- dzielenie przez zero.
- `FileNotFoundError` -- plik nie został odnaleziony.
- `RecursionError` -- przekroczony limit wywołań rekurencyjnych.
- ...

### Ćwiczenie I.1

Znajdź w dokumentacji Pythona opisy podanych wyżej wyjątków.

### Ćwiczenie I.2

Dla każdego z podanych wyżej wyjątków napisz program, który go zgłosi.

## Hierarchia wyjątków

Wyjątki w Pythonie tworzą hierarchię opartą o dziedziczenie, przy czym klasa bazowa dla wszystkich wyjątków to `BaseException` (czyli z tej klasy wszystkie wyjątki dziedziczą). Poniżej podaję szczytowy fragment tej hierarchii (pełną listę znajdziesz [tutaj](https://docs.python.org/3/library/exceptions.html)):

- `BaseException` -- klasa bazowa dla wszystkich wyjątków.
  - `SystemExit` -- wyjątek zgłaszany przez funkcję `sys.exit()`.
  - `KeyboardInterrupt` -- wyjątek zgłaszany przez przerwanie wysłane z klawiatury (`Ctrl+C`).
  - `GeneratorExit` -- wyjątek zgłaszany przez generator lub współprogram, gdy jest zamykany.
  - `Exception` -- klasa bazowa dla wszystkich wyjątków z wyjątkiem `SystemExit`, `KeyboardInterrupt`, `BaseExceptionGroup` i `GeneratorExit`. Innymi słowy, wyjątki zgłaszane w trakcie normalnego działania programu dziedziczą z `Exception`.

Znaczna większość wyjątków dziedziczy z klasy `Exception`. Niektóre wyjątki w tej grupie rozgałęziają się na dalsze, bardziej specjalistyczne. Przykładowo:

- `BaseException`
  - `Exception`
    - `ArithmeticError`
      - `ZeroDivisionError`
      - `OverflowError`
      - `FloatingPointError`

albo

- `BaseException`
  - `Exception`
    - `LookupError`
      - `IndexError`
      - `KeyError`

## Obsługa wyjątków, instrukcja `try`

`try` jest instrukcją złożoną służącą do obsługi wyjątków. Formalny opis składni instrukcji `try` znajdziesz [tutaj](https://docs.python.org/3/reference/compound_stmts.html#the-try-statement).

Fakt, że `try` jest instrukcją złożoną oznacza, że musi zawierać blok kodu z sekwencją instrukcji:

```python
try:
    # blok kodu
```

Po bloku `try` następują bloki `except`, `else` i `finally` w różnych możliwych kombinacjach, przy czym **musi** wystąpić co najmniej jeden z bloków `except` lub `finally`.

Rola poszczególnych bloków jest następująca:

- `try` -- blok, w którym może powstać wyjątek.
- `except` -- blok, który obsługuje wyjątek.
- `else` -- blok, który jest wykonywany, jeśli wyjątek nie powstał.
- `finally` -- blok, który jest wykonywany zawsze, niezależnie od tego czy wyjątek powstał czy nie.

Blok `except` jest opcjonalny i może występować wielokrotnie. Jeśli `except` jest wielokrotny, to wyjątek zostanie obsłużony przez pierwszy pasujący `except`. Bloki `else` i `finally` są również opcjonalne. Jeśli bloku `except` nie ma, to po bloku `try` musi wystąpić blok `finally`.

Nagłówek bloku `except` (tj. pierwszy wiersz bloku) zawiera nazwę wyjątku, który ma być obsłużony w bloku. Może to być nazwa klasy wyjątku lub krotka nazw klas wyjątków. Jeśli w bloku `except` nie ma nazwy wyjątku, to blok obsługuje wszystkie wyjątki (co jest zwykle złym pomysłem).

Aby uzyskać dostęp do obiektu wyjątku (np. w celu wyświetlenia komunikatu o błędzie), stosujemy składnię `except <wyjątek> as <zmienna>`. Zmienna ta jest dostępna w bloku `except` i zawiera instancję zgłoszonego wyjątku. Przykładowo:

```python
except OSError as e:
    print(f"Wystąpił błąd: {e}")
```

Zmienna `e` przechowuje tu obiekt wyjątku, którego tekstowa reprezentacja zwykle opisuje przyczynę błędu.

### Przykład I.1

```python
{{< include src/try_except_ZDE.py >}}
```

## Rola dziedziczenia w obsłudze wyjątków

Dziedziczenie w Pythonie odgrywa istotną rolę w obsłudze wyjątków. Blok `except` obsługuje wyjątki, które są instancjami klas wyjątków wymienionych w nagłówku bloku. Jeśli wyjątek jest instancją klasy, która dziedziczy po klasie wymienionej w nagłówku bloku, to wyjątek również zostanie obsłużony.

### Przykład I.2

```python
{{< include src/try_except_AE.py >}}
```

## Jak obsługiwać wyjątki

Staramy się przechwytywać te wyjątki, dla których jesteśmy w stanie podjąć jakieś działania naprawcze. Wyjątek, którego nie jesteśmy w stanie w żaden sensowny sposób obsłużyć, powinien być naturalnie przekazywany na wyższy poziom programu.

### Przykład I.3

Program wczytuje od użytkownika liczbę całkowitą i wypisuje informację o jej parzystości.

Wartość zwracana przez `input()` jest zawsze łańcuchem znaków, wartość tę konwertujemy na liczbę całkowitą za pomocą funkcji `int()`. Jednak użytkownik może podać coś innego niż liczba całkowita, coś czego `int()` nie jest w stanie skonwertować.
Jeśli tak się stanie, to `int()` zgłosi wyjątek `ValueError`. Program nie jest w stanie podać liczby za użytkownika, może jednak wyświetlić komunikat o błędzie i ponowić próbę wczytania liczby. A zatem w tym przypadku wyjątek może być sensownie obsłużony.

```python
{{< include src/try_except_even_odd.py >}}
```

Warto wiedzieć, że `input()` może również zgłosić `EOFError`, jeśli użytkownik wyśle sygnał końca strumienia (Ctrl+D w systemach Unix, Ctrl+Z w Windows). W powyższym przykładzie pomijamy ten przypadek dla przejrzystości.

---

W powyższym programie łatwo zgadnąć, jaki wyjątek zostanie zgłoszony, jeśli użytkownik poda coś innego niż liczba całkowita: `ValueError` bo typ argumentu jest prawidłowy, ale nie jest prawidłowa wartość. Czasem jednak trudno jest przewidzieć, jaki wyjątek zostanie zgłoszony. W takim przypadku:

- wykonaj eksperymenty testując różne scenariusze;
- zajrzyj do dokumentacji.

## `finally`

Blok `finally` jest wykonywany zawsze, niezależnie od tego czy wyjątek został zgłoszony czy nie, czy został obsłużony czy nie. Blok `finally` jest wykonywany nawet wtedy, gdy w bloku `try` wystąpił `return` lub `break`. Cel bloku `finally` to akcje czyszczące, które muszą być wykonane niezależnie od tego, co się stało w `try`, `except` i `else`. Typowym zastosowaniem `finally` jest zamykanie plików, zamykanie połączeń sieciowych, zwalnianie zasobów, itp.

### Ćwiczenie I.3

Napisz programy testujące działanie `finally` w różnych scenariuszach. Sprawdź, czy blok `finally` jest rzeczywiście zawsze wykonywany.

### Przykład I.4

Nieco bardziej realistyczny przykład. Skrypt `file_size_v1.py` oblicza rozmiar pliku w bajtach. Działa z wiersza poleceń. Przyjmuje dokładnie jeden argument, który jest nazwą pliku. Wyświetla rozmiar pliku w bajtach lub komunikat o błędzie. Program obsługuje dwa wyjątki: `FileNotFoundError` i `OSError`. W bloku `finally` zostaje podjęta próba zamknięcia pliku w kolejnym bloku `try`. Postępujemy w ten sposób, ponieważ otwarcie pliku może się nie powieść i wtedy zmienna `f` nie będzie istnieć.

```python
{{< include src/file_size_v1.py >}}
```

Zwróć uwagę, że `return` w bloku `else` nie zapobiega wykonaniu bloku `finally` — Python wykonuje `finally` przed faktycznym zwróceniem wartości z funkcji.

## Menedżer kontekstu

Menedżer kontekstu to mechanizm, który umożliwia efektywne zarządzanie zasobami, takimi jak pliki, połączenia sieciowe, itp. Podstawowym przykładem zastosowania menedżera kontekstu jest otwieranie pliku. Wykorzystuje się do tego instrukcję `with` i funkcję `open()`. Użycie menedżera kontekstu jest zalecane w tej sytuacji, gdyż zapewnia ono, że plik zostanie zawsze zamknięty, nawet jeśli w trakcie pracy z plikiem zostanie zgłoszony wyjątek. Dzięki temu nie trzeba pisać bloku `finally` do zamykania pliku.

### Przykład I.5

Program `file_size_v2.py` jest modyfikacją programu `file_size_v1.py`. W tej wersji plik jest otwierany tą samą funkcją `open()`, ale w managerze kontekstu. Manager kontekstu dla funkcji `open()` zapewnia zamknięcie pliku w każdym przypadku, nawet jeśli w trakcie pracy z plikiem zostanie zgłoszony wyjątek. 

```python
{{< include src/file_size_v2.py >}}
```

## Instrukcja `raise`

Instrukcja `raise` służy do zgłaszania (rzucania) wyjątków. Może być użyta w dwóch postaciach:

- `raise` -- ponownie zgłasza wyjątek aktualnie obsługiwany w bloku `except`. Użycie `raise` bez argumentu poza blokiem `except` spowoduje zgłoszenie `RuntimeError`.
- `raise <wyjątek>` -- rzuca wyjątek, którego nazwa jest podana po słowie kluczowym `raise`.

Gdy rzucany jest konkretny wyjątek, to można dodatkowo podać go z argumentem tekstowym stanowiącym opis sytuacji, w której wyjątek został zgłoszony.

Pierwsza sytuacja:

```python
try:
    # blok kodu
except <wyjątek>:
    # blok obsługi wyjątku
    raise  # Ponownie zgłoś obsługiwany wyjątek.
```

Druga sytuacja:

```python
x = -1

if x < 0:
    raise ValueError("x nie może być ujemne")
```

### Przykład I.6

Funkcja obliczająca średnią arytmetyczną z sekwencji liczb. Funkcja zgłasza wyjątek `ValueError`, jeśli sekwencja jest pusta.

```python
{{< include src/average.py >}}
```

## Traceback

Traceback, czyli ślad stosu, to lista wywołań funkcji, które doprowadziły do zgłoszenia wyjątku. Traceback jest wyświetlany w momencie zgłoszenia wyjątku. 

### Przykład I.7

```python
{{< include src/traceback_example.py >}}
```

Wynik działania programu:

```
Traceback (most recent call last):
  File "/home/tomek/Dokumenty/PPwAD2/repo/src/traceback_example.py", line 11, in <module>
    f()
  File "/home/tomek/Dokumenty/PPwAD2/repo/src/traceback_example.py", line 3, in f
    g()
  File "/home/tomek/Dokumenty/PPwAD2/repo/src/traceback_example.py", line 6, in g
    h()
  File "/home/tomek/Dokumenty/PPwAD2/repo/src/traceback_example.py", line 9, in h
    raise Exception("Błąd")
Exception: Błąd
```

Widzimy listę wywołań funkcji, które doprowadziły do zgłoszenia wyjątku. Każde wywołanie jest opisane w formacie:

```
  File "<nazwa_pliku>", line <numer_linii>, in <nazwa_funkcji lub modułu>
    <kod>
```

Kolejność elementów listy jest odwrotna do kolejności wywołań. Ostatni element listy to miejsce, w którym wyjątek został zgłoszony. W tym przypadku jest to funkcja `h()` w linii 11 pliku `traceback_example.py`.

Traceback jest bardzo pomocny w diagnozowaniu błędów. Dzięki niemu można zlokalizować miejsce, w którym błąd został zgłoszony, a także zrozumieć, jaki był kontekst, w którym to się stało.

Odkładanie się kolejnych wywołań funkcji na stosie bardzo ładnie wizualizuje serwis [pythontutor.com](http://pythontutor.com/visualize.html#mode=edit). 

### Ćwiczenie I.4

Wykonaj program `traceback_example.py` na [pythontutor.com](http://pythontutor.com/visualize.html#mode=edit). Zobacz, jak wygląda stos wywołań funkcji w momencie zgłoszenia wyjątku.

# Do poczytania

[EAFP](https://docs.python.org/3/glossary.html#term-eafp) vs [LBYL](https://docs.python.org/3/glossary.html#term-lbyl)

- EAFP -- Easier to ask for forgiveness than permission.
- LBYL -- Look before you leap.

Oba terminy opisują dwa style programowania defensywnego. Porównajmy je na przykładzie dostępu do klucza w słowniku:

```python
# LBYL — najpierw sprawdzamy, potem działamy
if "klucz" in d:
    wartosc = d["klucz"]
else:
    wartosc = "domyślna"
```

```python
# EAFP — próbujemy działać, a wyjątek obsługujemy gdy się pojawi
try:
    wartosc = d["klucz"]
except KeyError:
    wartosc = "domyślna"
```

W Pythonie idiomatyczne jest podejście EAFP, ponieważ obsługa wyjątków jest wbudowana w język i tania, a sprawdzanie warunków z góry bywa zawodne (np. plik może zniknąć między sprawdzeniem a otwarciem).

